name: "Run Endtest functional tests"
description: "Register a deployment event with Endtest and run the functional tests"
branding:
  icon: play-circle
  color: white
inputs:
  app-id:
    description: 'The Endtest App ID for your account. You can get it from the https://endtest.io/settings page.'
    required: true
  app-code:
    description: 'The Endtest App Code for your account. You can get it from the https://endtest.io/settings page.'
    required: true
  api-request:
    description: 'The Endtest API request for starting the test execution.'
    required: true
  number-of-loops:
    description: 'The number of times the API request for fetching the results will be sent once every 30 seconds.'
    required: true

outputs:
  test-suite-name:
    description: "The name of the test suite"
  configuration:
    description: "The configuration of the machine or mobile device on which the test was executed"
  test-cases:
    description: "The number of test cases"
  passed:
    description: "The number of assertions that have passed"
  failed:
    description: "The number of assertions that have failed"
  errors:
    description: "The number of errors that have been encountered"
  start_time:
    description: "The timestamp for the start of the test execution."
  end_time:
    description: "The timestamp for the end of the test execution."
  detailed_logs:
    description: "The detailed logs for the test execution"
  screenshots_and_video:
    description: "The URLs for the screenshts and video recordings of the test execution"

runs:
  using: "composite"
  steps:
    - run: sudo apt-get install jq
      shell: bash 
    - run: sudo chmod +x ${{ github.action_path }}/test.sh
      shell: bash 
    - run: ${{ github.action_path }}/test.sh {{ inputs.app-id }} {{ inputs.app-code }} {{ inputs.api-request }} {{ inputs.number-of-loops }}
      shell: bash
